### ISSUE TITLE
CIDR Erweiterung in IP Nertwork

### ISSUE THREAD

**Issue by tbluhmitsdave** [itsdave-de/msp#1]
Für neue Networks in IP Network stehen als CIDR lediglich 24 - 32 zur Verfügung.

Vorschlag für Vervollständigung:

24
16
12
8
32
31
30
29
28
27
26
25
23
22
21
20
19
18
17
15
14
13
11
10
9
7
6
5
4
3
2
1
![fewgs4grdthgdtfg #JPG](https://user-images.githubusercontent.com/81425025/112837316-051cbf00-909c-11eb-8369-a73f77daa069.JPG)

**Comment by itsdaveit** [comment]
in aktuellem Commit hinzugefügt.
