### ISSUE TITLE
IT Object Types - Vorschläge für weitere Einträge

### ISSUE THREAD

**Issue by tbluhmitsdave** [itsdave-de/msp#2]
Vorschläge für weitere Einträge -> Diese Liste ist unvollständig und darf gerne laufend erweitert werden.

Synology NAS
Gigaset DECT Basis
FreeNAS
pfSense Firewall
HP Drucker
Kyocera Drucker
Brother Drucker
Canon Drucker
Lexware Drucker
OKI Drucker
Ricoh Drucker
Samsung Drucker
Epson Drucker
NextCloud
ZyXEL VDSL Modem
DrayTek VDSL Modem
Grandstream SIP-Gateway
Cisco SIP-Gateway
Patton SIP-Gateway
FritzBox / HorstBox
myUTN USB-Server
Unifi Controller
AXIS IP-Kamera
Grandstream IP-Kamera
Windows Client
Linux/Unix Client
Windows Client VM
Panasonic PBX
Agfeo PBX
Auerswald PBX
Telekom PBX
Starface PBX
3CX PBX
SNOM IP-Telefon
Gigaset IP-Telefon
Grandstream IP-Telefon
Yealink IP-Telefon

**Comment by itsdaveit** [comment]
Lass uns die Object Types lokal pflegen. Ich habe sorgen bzgl. der Verwendung der Markennamen.
Bitte so einpflegen, unter Berücksichtigung der Änderungen:
Lexmark Drucker (statt Lexware)
FritzBox Router (nicht / Horstbox)
Linux Client (nicht Linux/Unix Client)
Gigaset DECT Basis (ggf. zusätzlich Gigaset IP-Telefon)
