### ISSUE TITLE
Presets funktionieren nicht

### ISSUE THREAD

**Issue by itsdaveit** [itsdave-de/msp#3]
Teilweise sind diese ohne Funktion oder machen die GUI Kaputt, weil sie Felder ausblenden.

![image](https://user-images.githubusercontent.com/9453135/158563394-ad0914f1-d1c8-4bf8-a530-db5b85b53132.png)

**Comment by itsdaveit** [comment]
![image](https://user-images.githubusercontent.com/9453135/159240711-fda10b9c-de10-4b42-a57d-69a50b35d358.png)
![image](https://user-images.githubusercontent.com/9453135/159240767-386e1bae-3f1f-4731-b28c-d936fb6b97c2.png)
![image](https://user-images.githubusercontent.com/9453135/159240830-674af38c-93ed-485c-b885-f0d1b2f3048a.png)

**Comment by itsdaveit** [comment]
@beatek1 wie war hier der stand?

**Comment by beatek1** [comment]
Anpassungen 8a574fa17afec62534f5fdaca28ce058497d9341

**Comment by beatek1** [comment]
Anpassungen im 7a752e01d861eb76bcf9702ee8d28f32e8ad33a1

**Comment by beatek1** [comment]
erledigt mit 9ab4157d86cdb8333ce6a46fd37b9d34a84c1e7b
